'use client';

import { Network, X } from 'lucide-react';

import { useTelemetryStore } from '../../stores/telemetry-store';

export function ArchitectureCard({ onDismiss }: { onDismiss: () => void }) {
  const toolCount = useTelemetryStore((state) => state.registeredToolNames.length);
  const totalCalls = useTelemetryStore((state) => state.totalCalls);

  return <div className="fixed inset-0 z-40 flex items-start justify-center bg-slate-950/20 p-6 pt-24" role="dialog" aria-modal="true" aria-labelledby="architecture-card-title"><section className="w-full max-w-2xl rounded-xl border border-slate-200 bg-white p-5 shadow-xl shadow-slate-400/30"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="inline-flex h-9 w-9 items-center justify-center rounded-lg bg-violet-50 text-violet-700"><Network size={18} /></span><div><h2 id="architecture-card-title" className="text-base font-semibold text-slate-950">One command layer, two interfaces</h2><p className="mt-1 text-sm text-slate-600">Humans and agents make the same state changes through the same commands.</p></div></div><button type="button" onClick={onDismiss} aria-label="Close architecture card" className="text-slate-400 hover:text-slate-700"><X size={18} /></button></div><div className="mt-5 grid items-center gap-3 text-center text-sm font-medium md:grid-cols-[1fr_auto_1.3fr_auto_1fr]"><div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-4 text-slate-800">Human UI</div><span className="text-slate-400">→</span><div className="rounded-lg border border-violet-200 bg-violet-50 px-3 py-4 text-violet-950">Command layer<br /><span className="text-xs font-normal text-violet-700">policy checks · undo · activity</span></div><span className="text-slate-400">←</span><div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-4 text-slate-800">AI agent<br /><span className="text-xs font-normal text-slate-500">WebMCP tools</span></div></div><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Live tools</p><p className="mt-1 text-xl font-semibold text-slate-900">{toolCount}</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">Tool calls</p><p className="mt-1 text-xl font-semibold text-slate-900">{totalCalls}</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">DOM automation</p><p className="mt-1 text-xl font-semibold text-slate-900">0 lines</p></div></div></section></div>;
}
